import type { Metadata } from "next";
import "./globals.css";
import { ThemeProviderWrapper } from './../theme/ThemeProviderWrapper';




export const metadata: Metadata = {
  title: "IranianAcademy",
  description: "Generated by 2*Mamad + Ali",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ThemeProviderWrapper>
          {children}
        </ThemeProviderWrapper>
      </body>
    </html>
  );
}
